[package]
name = "tauri-specta"
description = "Completely typesafe Tauri commands"
version = "1.0.2"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/README.md", "/LICENCE"]
repository = "https://github.com/oscartbeaumont/tauri-specta"
documentation = "https://docs.rs/tauri-specta/latest/tauri-specta"
keywords = ["async", "specta", "rspc", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
js_doc = ["specta/js_doc"]
typescript = ["specta/typescript"]

[dependencies]
specta = { workspace = true, features = ["functions", "tauri"] }
tauri-specta-macros = { path = "./macros" }
serde = { workspace = true }
serde_json = "1.0.106"
tauri = { workspace = true }
thiserror = "1.0.48"
heck = "0.4.1"
indoc = "2.0.3"

[dev-dependencies]
doc-comment = "0.3.3"

[workspace]
members = [
    "examples/app/src-tauri",
    "examples/custom-plugin/app/src-tauri",
    "examples/custom-plugin/plugin",
    "macros",
]

[workspace.dependencies]
specta = { version = "^2.0.0-rc.3" }
serde = "1.0.188"
tauri = "1.4.1"

[patch.crates-io]
specta = { git = "https://github.com/oscartbeaumont/specta", rev = "efdd024fd1ab2a569ffe9d7fc484c419eb6ef9c5" }
