[package]
name = "tauri-specta"
description = "Completely typesafe Tauri commands"
version = "0.0.2"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/README.md", "/LICENCE"]
repository = "https://github.com/oscartbeaumont/tauri-specta"
documentation = "https://docs.rs/tauri-specta/latest/tauri-specta"
keywords = ["async", "specta", "rspc", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

[features]
openapi = ["dep:openapiv3", "specta/openapi"]

[dependencies]
# specta = { version = "0.0.6", features = ["function", "tauri"] }
specta = { git = "https://github.com/oscartbeaumont/rspc", branch = "tauri-specta-changes", features = ["function", "tauri"] }
serde = "1.0.147"
serde_json = "1.0.87"
tauri = "1.1.1"
thiserror = "1.0.37"
heck = "0.4.0"

openapiv3 = { version = "1.0.1", optional = true }

[workspace]
members = [
    "example/src-tauri",
]
